services:
  # --- DATABASE: MongoDB ---
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- BACKEND: Node.js / Express ---
  api:
    build: ./backend
    container_name: node
    restart: always
    environment:
      NODE_ENV: development
      DB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/meanapp?authSource=admin
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

# Volumi per la persistenza dei dati
volumes:
  mongo_data:
