name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Scarica il codice dalla repository
      - name: Checkout del codice
        uses: actions/checkout@v4

      # 2. Prepara l'ambiente Node.js per la build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
    #   - name: Build Backend
    #     run: |
    #       cd backend
    #       npm ci
    #       npm run build
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
            host: ${{ secrets.LAB_SERVER_HOST }}
            username: ${{ secrets.LAB_SERVER_USER }}
            password: ${{ secrets.LAB_SERVER_PASSWORD }}
            # key: ${{ secrets.LAB_SERVER_SSH_KEY }}
            port: ${{ secrets.LAB_SERVER_PORT }} 
            # Specifica le cartelle e i file che servono alla tua macchina per far girare docker
            source: "frontend/dist/, backend/" 
            # source: "frontend/dist/, backend/, docker-compose.yml, Dockerfile" 
            # Specifica il percorso esatto sul server del laboratorio dove vuoi i file
            target: "/home/web/site252623/"
