name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Scarica il codice dalla repository
      - name: Checkout del codice
        uses: actions/checkout@v4

      # 2. Prepara l'ambiente Node.js per la build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup Backend
        run: |
          cd backend
          npm ci

      - name: Rimuovi node_modules del backend prima del deploy
        run: rm -rf backend/node_modules

      - name: Crea file .env
        run: |
          echo "MONGO_USER=${{ secrets.LAB_MONGO_USER }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.LAB_MONGO_PW }}" >> .env
          echo "MONGO_DATABASE=${{ secrets.LAB_MONGO_DATABASE }}" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Build Frontend
        run: |
          cd frontend
          npm ci --legacy-peer-deps
          npm run build

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LAB_SERVER_HOST }}
          username: ${{ secrets.LAB_SERVER_USER }}
          password: ${{ secrets.LAB_SERVER_PASSWORD }}
          port: ${{ secrets.LAB_SERVER_PORT }}
          source: "frontend/dist/, backend/, docker-compose.yaml, .env"
          target: "/home/web/site252623/html"
          overwrite: true
          debug: true
